---
title: "tt_beer_fest"
author: "Katie Kotasek"
date: "October 21, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = T, results = 'hide', error = F, warning = F, message = F}
library(tidyverse)
library(lubridate)
library(mmbtools)
library(tidytuesdayR)
library(gganimate)
library(transformr)
library(maps)
library(ggmap)       
library(sf)
library(statebins)

mmb_load_fonts()
```

```{r download data}
beer_awards <- as_tibble(read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-20/beer_awards.csv'))

beer_awards <- beer_awards %>%
  # add region column to the data set
  mutate(region = case_when(state %in% c("ME", "MA", "RI", "CT", "NH", "VT", "NY", "PA", "NJ", "DE", "MD") ~ "Northeast",
                            state %in% c("WV", "VA", "KY", "TN", "NC", "SC", "GA", "AL", "MS", "AR", "LA", "FL", "DC") ~ "Southeast",
                            state %in% c("OH", "IN", "MI", "IL", "MO", "WI", "MN", "IA", "KS", "NE", "SD", "ND") ~ "Midwest",
                            state %in% c("TX", "OK", "NM", "AZ") ~ "Southwest",
                            state %in% c("CO", "WY", "MT", "ID", "WA", "wa", "OR", "UT", "NV", "CA", "AK", "Ak", "HI") ~ "West"),
         medalOrder = fct_relevel(medal, "Gold", "Silver", "Bronze"))  # reorder displayed values
```

## Version 1
```{r static plot}
# create a static plot - used to see how the data is layed out before creating the animation
beer_awards %>% 
  ggplot(aes(x = medalOrder, group = region, fill = region)) +
  geom_bar() +
  scale_fill_mncol(palette = "main", discrete = T) +
  geom_text(stat = "count", aes(label = ..count..), vjust = 1) +
  scale_y_continuous(limits = c(0, 1000)) +
  facet_wrap(vars(region)) +
  labs(title = "Count of Medals by Region", 
       x = "Medals",
       y = "Count") +
  theme_mmb_basic(legend.position = "none",
                  axis.title.x = element_text(size = 12), 
                  axis.title.y = element_text(size = 12))
```

```{r create animation}
# create animation
anim_beer_fest <- beer_awards %>% 
  ggplot(aes(x = medalOrder, group = region, fill = region)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.75) +  # add counts for each medal type to the plot
  scale_y_continuous(limits = c(0, 1000)) +  # set the minimum and maximum values for the y-axis
  scale_fill_mncol(palette = "main", discrete = T) +  # set color scheme for the bars
  labs(title = "Count of Medals by Region",  # add plot title
       subtitle = "Region: {next_state}",  # add plot subtitle that changes with each state change
       x = "Medal Types",  # add x-axis title
       y = "Total Count") +  # add y-axis title
  theme_mmb_basic(legend.position = "none",
                  axis.title.x = element_text(size = 12),  # set text size for x-axis
                  axis.title.y = element_text(size = 12)) + # set text size for y-axis 
  transition_states(states = region, transition_length = 1, state_length = 30) 
#+
#  enter_grow() +
#  exit_fade()
# adjust the output size and frames per second values
animate(anim_beer_fest, 
        fps = 5,  # the number of frames per second
        width = 400, 
        height = 400)

# save animation as a gif
anim_save("Week of 10.19.20/Beer Awards Fest (5 fps).gif")
```

## Version 2
Create map and display counts by year
```{r}
beer_awards <- beer_awards %>%
  mutate(state = case_when(state == "AL" ~ "alabama", state == "AK" ~ "alaska",
                           state == "AZ" ~ "arizona", state == "AR" ~ "arkansas",
                           state == "CA" ~ "california", state == "CO" ~ "colorado",
                           state == "CT" ~ "connecticut", state == "DE" ~ "delaware",
                           state == "FL" ~ "florida", state == "GA" ~ "georgia",
                           state == "HI" ~ "hawaii", state == "ID" ~ "idaho",
                           state == "IL" ~ "illinois", state == "IN" ~ "indiana",
                           state == "IA" ~ "iowa", state == "KS" ~ "kansas",
                           state == "KY" ~ "kentucky", state == "LA" ~ "louisiana",
                           state == "ME" ~ "maine", state == "MD" ~ "maryland",
                           state == "MA" ~ "massachusetts", state == "MI" ~ "michigan",
                           state == "MN" ~ "minnesota", state == "MS" ~ "mississippi",
                           state == "MO" ~ "missouri", state == "MT" ~ "montana",
                           state == "NE" ~ "nebraska", state == "NV" ~ "nevada",
                           state == "NH" ~ "new hampshire", state == "NJ" ~ "new jersey",
                           state == "NM" ~ "new mexico", state == "NY" ~ "new york",
                           state == "NC" ~ "north carolina", state == "ND" ~ "north dakota",
                           state == "OH" ~ "ohio", state == "OK" ~ "oklahoma",
                           state == "OR" ~ "oregon", state == "PA" ~ "pennsylvania",
                           state == "RI" ~ "rhode island", state == "SC" ~ "south carolina",
                           state == "SD" ~ "south dakota", state == "TN" ~ "tennessee",
                           state == "TX" ~ "texas", state == "UT" ~ "utah",
                           state == "VT" ~ "vermont", state == "VA" ~ "virginia",
                           state == "WA" ~ "washington", state == "WV" ~ "west virginia",
                           state == "WI" ~ "wisconsin", state == "WY" ~ "wyoming"))
```

```{r}
states_map <- map_data("state") %>% 
  select(-c(group, order, subregion))

beer_awards <- beer_awards %>%
  group_by(state, year) %>% 
  summarize(medals_total = n()) %>% 
  mutate(medals_total = ifelse(is.na(medals_total), 0, medals_total)) %>% 
  ungroup() %>% 
  inner_join(states_map, by = c("state" = "region"))
  
```


```{r}
state_anim <- beer_awards %>% 
  filter(year >= 2000) %>%
  ggplot(aes(state = state, fill = medals_total)) +
  borders("state", na.rm = TRUE, colour = "grey50") +
  geom_polygon(aes(x = long, y = lat, group = state, fill = medals_total)) +
  #geom_statebins(na.rm = T) +
  scale_fill_mncol(palette = "heat", reverse = TRUE, discrete = FALSE) +
  labs(title = "Total Medal Count by State",
       subtitle = "Year: {closest_state}",
       fill = "") +
  theme_mmb_map() +
  theme(legend.title = element_blank(),
        legend.position = c(0, 0), 
        legend.justification = c(0, 0),
        legend.direction = "horizontal", 
        plot.title = element_text(size = 16, face = "bold"), 
        plot.subtitle = element_text(size = 14)) +
  transition_states(year, transition_length = 20, state_length = 100)

animate(state_anim, 
        fps = 2,  # the number of frames per second
        width = 500, 
        height = 350)

anim_save("Week of 10.19.20/Beer Awards - State Map.gif")
```

